import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  template: `
  <p>
    input-button-unit works!
    The title is: {{ title }}
  </p>
 
<input #inputElementValue [value]="title"
  (keyup.enter)="changeTitle($event.target.value)">
<button (click)="changeTitle(inputElementValue.value)">
  Save
</button>
`,
  styleUrls: ['./input-button-unit.component.css'],
})
export class InputButtonUnitComponent implements OnInit {
  title = 'Hello World';

  constructor() {
    console.log('new');
    //this.changeTitle('I love Angular');
    console.log(this.title);
  }

  ngOnInit(): void {
    // setTimeout(() => {
    //   this.title = 'This is not the title you are looking for';
    // }, 3000);
  }
  changeTitle(newTitle: string): void {
    console.log(newTitle);
    this.title = newTitle;
  }
  generateTitle(): string {
    return 'This title was generated by a method.';
  }
}
